// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `operation_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

KeepOperationReservation keepReserveOperation({required String operationId}) =>
    WorkoutCoreRustLib.instance.api.crateApiKeepKeepReserveOperation(
      operationId: operationId,
    );

bool keepCancelOperation({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiKeepKeepCancelOperation(
      operationHandle: operationHandle,
    );

bool keepReleaseOperation({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiKeepKeepReleaseOperation(
      operationHandle: operationHandle,
    );

Future<KeepLoginResult> keepLogin({
  required String operationHandle,
  required String account,
  required String password,
}) => WorkoutCoreRustLib.instance.api.crateApiKeepKeepLogin(
  operationHandle: operationHandle,
  account: account,
  password: password,
);

Future<List<KeepWorkoutResult>> keepListWorkouts({
  required String operationHandle,
  required String token,
  required PlatformInt64 fromSeconds,
  required PlatformInt64 toSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiKeepKeepListWorkouts(
  operationHandle: operationHandle,
  token: token,
  fromSeconds: fromSeconds,
  toSeconds: toSeconds,
);

Future<Uint8List> keepDownloadFit({
  required String operationHandle,
  required String token,
  required String workoutId,
}) => WorkoutCoreRustLib.instance.api.crateApiKeepKeepDownloadFit(
  operationHandle: operationHandle,
  token: token,
  workoutId: workoutId,
);

class KeepLoginResult {
  final String token;

  const KeepLoginResult({required this.token});

  @override
  int get hashCode => token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeepLoginResult &&
          runtimeType == other.runtimeType &&
          token == other.token;
}

class KeepOperationReservation {
  final String handle;

  const KeepOperationReservation({required this.handle});

  @override
  int get hashCode => handle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeepOperationReservation &&
          runtimeType == other.runtimeType &&
          handle == other.handle;
}

class KeepWorkoutResult {
  final String id;
  final String title;
  final double startTimeSeconds;
  final double endTimeSeconds;
  final double durationSeconds;
  final double? distanceMeters;
  final bool indoor;

  const KeepWorkoutResult({
    required this.id,
    required this.title,
    required this.startTimeSeconds,
    required this.endTimeSeconds,
    required this.durationSeconds,
    this.distanceMeters,
    required this.indoor,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startTimeSeconds.hashCode ^
      endTimeSeconds.hashCode ^
      durationSeconds.hashCode ^
      distanceMeters.hashCode ^
      indoor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeepWorkoutResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startTimeSeconds == other.startTimeSeconds &&
          endTimeSeconds == other.endTimeSeconds &&
          durationSeconds == other.durationSeconds &&
          distanceMeters == other.distanceMeters &&
          indoor == other.indoor;
}
