// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `begin`, `begin`, `onelap_operation_error`, `operation_error_response`, `rate_limit_result`, `remote_activity_error`, `remote_activity_result`, `remote_activity_speed_result`, `remote_operation_error`, `reserve_for_refresh`, `reserve`, `reserve`, `token_result`, `upload_ffi_response`, `upload_operations`, `weather_stations`, `xingzhe_list_operation_error`, `xingzhe_list_operations`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UploadOperationEntry`, `UploadOperationError`, `UploadOperationRegistry`, `UploadOperationState`, `UploadOperation`, `XingzheListOperationEntry`, `XingzheListOperationError`, `XingzheListOperationRegistry`, `XingzheListOperationState`, `XingzheListOperation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `drop`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Flutter 调用的最小同步入口，直接复用已测试的核心规则。
bool isCommute({double? distanceMeters, required double durationSeconds}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleIsCommute(
      distanceMeters: distanceMeters,
      durationSeconds: durationSeconds,
    );

/// 计算与 Swift 兼容的同步幂等指纹；非法时间戳不会产生可持久化指纹。
String syncFingerprint({
  required String primarySourceId,
  required String primaryActivityId,
  required double startDateUnixSeconds,
  required List<String> supplementSourceIds,
  required String destination,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleSyncFingerprint(
  primarySourceId: primarySourceId,
  primaryActivityId: primaryActivityId,
  startDateUnixSeconds: startDateUnixSeconds,
  supplementSourceIds: supplementSourceIds,
  destination: destination,
);

/// 返回两个活动的匹配分数；不满足时间重叠或兜底容差时为 `null`。
double? activityMatchScore({
  required ActivityIntervalInput primary,
  required ActivityIntervalInput candidate,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleActivityMatchScore(
  primary: primary,
  candidate: candidate,
);

/// 返回候选活动中分数最高的原始下标；并列时保留最先出现者。
int? bestActivityMatchIndex({
  required ActivityIntervalInput primary,
  required List<ActivityIntervalInput> candidates,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleBestActivityMatchIndex(
  primary: primary,
  candidates: candidates,
);

/// 按已有 Swift 容差判断两个跨来源活动是否稳定去重。
bool stableDedupeMatches({
  required double startASeconds,
  required double distanceAMeters,
  required double startBSeconds,
  required double distanceBMeters,
  double? durationASeconds,
  double? durationBSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStableDedupeMatches(
  startASeconds: startASeconds,
  distanceAMeters: distanceAMeters,
  startBSeconds: startBSeconds,
  distanceBMeters: distanceBMeters,
  durationASeconds: durationASeconds,
  durationBSeconds: durationBSeconds,
);

/// 严格校验 FIT 并返回轨迹/心率内容质量摘要。
FitProbeSummary fitContentSummary({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleFitContentSummary(data: data);

bool isValidFit({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleIsValidFit(data: data);

/// 严格校验后原样返回 FIT；当前接口没有编辑参数。
Uint8List reencodeFit({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleReencodeFit(data: data);

/// 将一个完整的 HealthKit 训练包直接编码为标准 Activity FIT。
Future<Uint8List> encodeHealthWorkoutFit({
  required List<int> bundleJson,
  required int timezoneOffsetSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleEncodeHealthWorkoutFit(
  bundleJson: bundleJson,
  timezoneOffsetSeconds: timezoneOffsetSeconds,
);

/// 解码 FIT 为有界 Apple Health 写入草稿 JSON；本函数不访问健康资料库。
Future<Uint8List> decodeFitHealthDraft({
  required List<int> data,
  required String fingerprint,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleDecodeFitHealthDraft(
  data: data,
  fingerprint: fingerprint,
);

/// 使用行者网页登录契约换取短期 sessionid；凭据只用于本次请求，调用方负责安全保存返回值。
Future<String> xingzheLogin({
  required String account,
  required String password,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleXingzheLogin(
  account: account,
  password: password,
);

/// 使用旧 Swift 的顽鹿 MD5 登录契约换取 token 和 uid；调用方负责安全保存返回值。
Future<OnelapLoginResult> onelapLogin({
  required String account,
  required String password,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapLogin(
  account: account,
  password: password,
);

/// 换取并返回轮换后的会话；调用方必须把 token/uid/refreshToken 一起安全保存。
Future<OnelapLoginResult> onelapRefreshSession({
  required String refreshToken,
  required String uid,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapRefreshSession(
  refreshToken: refreshToken,
  uid: uid,
);

/// 预留顽鹿请求的取消句柄；与 Strava 请求共用有界、代际隔离的注册表。
StravaUploadReservation onelapReserveOperation({required String operationId}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapReserveOperation(
      operationId: operationId,
    );

bool onelapCancelOperation({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapCancelOperation(
      operationHandle: operationHandle,
    );

bool onelapReleaseOperation({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapReleaseOperation(
      operationHandle: operationHandle,
    );

/// 按旧 Swift 的 20 条分页、半开区间读取顽鹿骑行；会话只用于本次 Rust 请求。
Future<List<OnelapWorkoutResult>> onelapListWorkouts({
  required String token,
  required String uid,
  required PlatformInt64 fromSeconds,
  required PlatformInt64 toSeconds,
  required int timezoneOffsetSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapListWorkouts(
  token: token,
  uid: uid,
  fromSeconds: fromSeconds,
  toSeconds: toSeconds,
  timezoneOffsetSeconds: timezoneOffsetSeconds,
);

/// 读取顽鹿详情的 FIT 候选并仅返回严格校验后、内容质量最佳的一份 FIT。
Future<Uint8List> onelapDownloadFit({
  required String token,
  required String uid,
  required String activityId,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapDownloadFit(
  token: token,
  uid: uid,
  activityId: activityId,
);

/// 可取消的顽鹿分页读取，返回含日期边界余量的候选列表。
/// Flutter 必须按 start_time_local 的历史本地时区解析后执行精确半开区间过滤。
Future<List<OnelapWorkoutResult>> onelapListWorkoutsCancellable({
  required String operationHandle,
  required String token,
  required String uid,
  required PlatformInt64 fromSeconds,
  required PlatformInt64 toSeconds,
  required int timezoneOffsetSeconds,
}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapListWorkoutsCancellable(
      operationHandle: operationHandle,
      token: token,
      uid: uid,
      fromSeconds: fromSeconds,
      toSeconds: toSeconds,
      timezoneOffsetSeconds: timezoneOffsetSeconds,
    );

/// 可取消的顽鹿 FIT 下载；取消后不尝试下一个候选 URL。
Future<Uint8List> onelapDownloadFitCancellable({
  required String operationHandle,
  required String token,
  required String uid,
  required String activityId,
}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleOnelapDownloadFitCancellable(
      operationHandle: operationHandle,
      token: token,
      uid: uid,
      activityId: activityId,
    );

/// 读取行者 stream 并编码为标准 Activity FIT。必须先预留列表句柄以便取消。
Future<Uint8List> xingzheDownloadFit({
  required String operationHandle,
  required String sessionId,
  required String workoutId,
  required String title,
  required double startTimeSeconds,
  required double durationSeconds,
  double? distanceMeters,
  required int timezoneOffsetSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleXingzheDownloadFit(
  operationHandle: operationHandle,
  sessionId: sessionId,
  workoutId: workoutId,
  title: title,
  startTimeSeconds: startTimeSeconds,
  durationSeconds: durationSeconds,
  distanceMeters: distanceMeters,
  timezoneOffsetSeconds: timezoneOffsetSeconds,
);

/// 主源优先补传感器。`alignment` 为 `absolute` / `auto` / `manual`。
Uint8List mergeFitFiles({
  required List<int> primary,
  required List<Uint8List> supplements,
  required bool sensorsOnly,
  required String alignment,
  required int manualOffsetSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleMergeFitFiles(
  primary: primary,
  supplements: supplements,
  sensorsOnly: sensorsOnly,
  alignment: alignment,
  manualOffsetSeconds: manualOffsetSeconds,
);

Future<MergedFitResult> mergeFitFilesDetailed({
  required List<int> primary,
  required List<Uint8List> supplements,
  required bool sensorsOnly,
  required String alignment,
  required int manualOffsetSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleMergeFitFilesDetailed(
  primary: primary,
  supplements: supplements,
  sensorsOnly: sensorsOnly,
  alignment: alignment,
  manualOffsetSeconds: manualOffsetSeconds,
);

/// 修复已证明的 GPS 速度尖峰。
Uint8List fixFitSpeedSpikes({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleFixFitSpeedSpikes(data: data);

/// 把中国境内 GCJ-02 坐标改写为 WGS-84。
Uint8List rewriteFitGcjCoordinates({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleRewriteFitGcjCoordinates(
      data: data,
    );

/// 可取消的生产准备入口；复用有界、代际隔离的远端 operation handle。
/// 取消会丢弃天气网络 Future，退出时释放 handle。旧同步入口保留给兼容调用方。
Future<PreparedFitResult> prepareFitForUploadCancellable({
  required String operationHandle,
  required List<int> primary,
  required List<Uint8List> supplements,
  required bool gcjEnabled,
  VirtualPowerFillInput? virtualPower,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimplePrepareFitForUploadCancellable(
      operationHandle: operationHandle,
      primary: primary,
      supplements: supplements,
      gcjEnabled: gcjEnabled,
      virtualPower: virtualPower,
    );

/// 上传前固定顺序：补源合并 → 尖峰 → GCJ → 虚拟功率。
Future<PreparedFitResult> prepareFitForUpload({
  required List<int> primary,
  required List<Uint8List> supplements,
  required bool gcjEnabled,
  VirtualPowerFillInput? virtualPower,
}) => WorkoutCoreRustLib.instance.api.crateApiSimplePrepareFitForUpload(
  primary: primary,
  supplements: supplements,
  gcjEnabled: gcjEnabled,
  virtualPower: virtualPower,
);

/// 预留一个不可复用的行者列表读取句柄。调用方可在请求期间精确取消此代操作。
XingzheListReservation xingzheReserveList({required String operationId}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleXingzheReserveList(
      operationId: operationId,
    );

/// 按现有 `sessionid` 读取行者活动。必须先预留句柄，Future 结束时自动释放。
Future<List<XingzheWorkoutResult>> xingzheListWorkouts({
  required String operationHandle,
  required String sessionId,
  required PlatformInt64 fromSeconds,
  required PlatformInt64 toSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleXingzheListWorkouts(
  operationHandle: operationHandle,
  sessionId: sessionId,
  fromSeconds: fromSeconds,
  toSeconds: toSeconds,
);

/// 取消特定代际的行者列表读取；旧句柄不会影响后续相同逻辑 ID 的新操作。
bool xingzheCancelList({required String operationHandle}) => WorkoutCoreRustLib
    .instance
    .api
    .crateApiSimpleXingzheCancelList(operationHandle: operationHandle);

/// 释放尚未启动的行者列表读取预留句柄；运行中的操作由 Future 结束时自动释放。
bool xingzheReleaseList({required String operationHandle}) => WorkoutCoreRustLib
    .instance
    .api
    .crateApiSimpleXingzheReleaseList(operationHandle: operationHandle);

/// 原子执行同步状态校验/转换；返回值只有在完整成功后才可写回原生文件。
Uint8List syncStateApply({
  required List<int> stateJson,
  required List<int> commandJson,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleSyncStateApply(
  stateJson: stateJson,
  commandJson: commandJson,
);

/// 校验旧 Swift 恢复包并按同一 JSON/Base64 协议规范化返回。
Uint8List syncRecoveryReencode({required List<int> recoveryJson}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleSyncRecoveryReencode(
      recoveryJson: recoveryJson,
    );

/// 原子推进崩溃恢复事务；阶段转换和 FIT 哈希验证失败时不产生可写回字节。
Uint8List syncRecoveryApply({
  required List<int> recoveryJson,
  required List<int> commandJson,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleSyncRecoveryApply(
  recoveryJson: recoveryJson,
  commandJson: commandJson,
);

/// 远端活动预检排名：IoU 优先，其次 45 分钟开始差/时长，再其次稳定距离。
int? stravaBestRemoteActivityMatchIndex({
  required double startTimeSeconds,
  required double endTimeSeconds,
  double? distanceMeters,
  required List<StravaRemoteActivityResult> candidates,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimpleStravaBestRemoteActivityMatchIndex(
      startTimeSeconds: startTimeSeconds,
      endTimeSeconds: endTimeSeconds,
      distanceMeters: distanceMeters,
      candidates: candidates,
    );

/// 仅骑行参与异常速度判定；与 Swift 摘要、最佳成绩及综合峰值阈值一致。
bool stravaSpeedIsAnomalous({
  required String sportType,
  required double listedMaxSpeedMps,
  required double bestEffortPeakMps,
  required double maxSpeedMps,
  required double averageSpeedMps,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaSpeedIsAnomalous(
  sportType: sportType,
  listedMaxSpeedMps: listedMaxSpeedMps,
  bestEffortPeakMps: bestEffortPeakMps,
  maxSpeedMps: maxSpeedMps,
  averageSpeedMps: averageSpeedMps,
);

/// 最近一次该 token 的 API 响应限额；仅进程内有界缓存，时间戳明确标记数据时效。
StravaRateLimitResult? stravaRateLimitSnapshot({required String accessToken}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaRateLimitSnapshot(
      accessToken: accessToken,
    );

/// 读取当前 API 限额，429 带有效限额响应头时也返回结果。使用远端读取句柄取消。
Future<StravaRateLimitResult> stravaFetchRateLimitUsage({
  required String operationHandle,
  required String accessToken,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaFetchRateLimitUsage(
  operationHandle: operationHandle,
  accessToken: accessToken,
);

Future<StravaTokenResult> stravaExchangeCode({
  required String clientId,
  required String clientSecret,
  required String code,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaExchangeCode(
  clientId: clientId,
  clientSecret: clientSecret,
  code: code,
);

Future<StravaTokenResult> stravaRefreshToken({
  required String clientId,
  required String clientSecret,
  required String refreshToken,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaRefreshToken(
  clientId: clientId,
  clientSecret: clientSecret,
  refreshToken: refreshToken,
);

/// 首次上传。若返回 NeedsRefresh/Upload，调用方强制刷新并只调用一次
/// `strava_retry_upload_after_refresh`，不得再次调用本入口形成无限重试。
/// 仅供手写 Dart 安全门面调用；业务代码不得直接绕过门面的输入预检。
Future<StravaUploadFfiResponse> stravaUploadFit({
  required String operationHandle,
  required String accessToken,
  required List<int> fit,
  required String externalId,
  required String filename,
  required bool commute,
  String? description,
  String? name,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaUploadFit(
  operationHandle: operationHandle,
  accessToken: accessToken,
  fit: fit,
  externalId: externalId,
  filename: filename,
  commute: commute,
  description: description,
  name: name,
);

/// POST 401 后的唯一一次重放；本调用再次遇到 401 会直接返回 Unauthorized 硬失败。
/// 仅供手写 Dart 安全门面调用。
Future<StravaUploadFfiResponse> stravaRetryUploadAfterRefresh({
  required String operationHandle,
  required String accessToken,
  required List<int> fit,
  required String externalId,
  required String filename,
  required bool commute,
  String? description,
  String? name,
}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaRetryUploadAfterRefresh(
      operationHandle: operationHandle,
      accessToken: accessToken,
      fit: fit,
      externalId: externalId,
      filename: filename,
      commute: commute,
      description: description,
      name: name,
    );

/// poll 401 后以新 token 从同一 uploadId、同一 attempt 立即续跑；再次 401 直接失败。
/// 仅供手写 Dart 安全门面调用。
Future<StravaUploadFfiResponse> stravaResumeUploadPollAfterRefresh({
  required String operationHandle,
  required String accessToken,
  required String uploadId,
  required int pollAttempt,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimpleStravaResumeUploadPollAfterRefresh(
      operationHandle: operationHandle,
      accessToken: accessToken,
      uploadId: uploadId,
      pollAttempt: pollAttempt,
    );

/// 上传完成后的可选后处理：从 Strava 主页动态隐藏活动，活动可见性不变。
Future<void> stravaHideActivityFromHome({
  required String accessToken,
  required String activityId,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaHideActivityFromHome(
  accessToken: accessToken,
  activityId: activityId,
);

/// 拉取 Strava 远端活动列表。调用前先用 `strava_reserve_remote_read` 获取 handle，
/// 运行中可通过 `strava_cancel_remote_read` 取消；handle 在 Future 结束后自动释放。
Future<List<StravaRemoteActivityResult>> stravaListRemoteActivities({
  required String operationHandle,
  required String accessToken,
  required PlatformInt64 afterSeconds,
  required PlatformInt64 beforeSeconds,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaListRemoteActivities(
  operationHandle: operationHandle,
  accessToken: accessToken,
  afterSeconds: afterSeconds,
  beforeSeconds: beforeSeconds,
);

/// 上传成功后的幂等元数据更新。调用前预留 operation handle；失败不应重新上传 FIT。
Future<void> stravaUpdateActivityMetadata({
  required String operationHandle,
  required String accessToken,
  required String activityId,
  required String name,
  required bool commute,
  String? descriptionNote,
}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaUpdateActivityMetadata(
      operationHandle: operationHandle,
      accessToken: accessToken,
      activityId: activityId,
      name: name,
      commute: commute,
      descriptionNote: descriptionNote,
    );

/// 拉取单条 Strava 活动的摘要最高速与 best_efforts 峰值；404 返回 `null`。
/// 调用约束与 `strava_list_remote_activities` 相同，避免读取任务无法中止。
Future<StravaActivitySpeedResult?> stravaFetchRemoteActivitySpeed({
  required String operationHandle,
  required String accessToken,
  required String activityId,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimpleStravaFetchRemoteActivitySpeed(
      operationHandle: operationHandle,
      accessToken: accessToken,
      activityId: activityId,
    );

/// 解析原生网页通道返回的单页训练 JSON；分页和日期过滤由调用方负责。
List<StravaRemoteActivityResult> stravaParseWebRemoteActivities({
  required List<int> responseJson,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimpleStravaParseWebRemoteActivities(responseJson: responseJson);

List<StravaActivitySpeedResult> stravaParseWebListedActivitySpeeds({
  required List<int> responseJson,
}) => WorkoutCoreRustLib.instance.api
    .crateApiSimpleStravaParseWebListedActivitySpeeds(
      responseJson: responseJson,
    );

/// 网页速度解析，不接触 Cookie；非骑车返回 null，坏页面返回明确错误。
StravaActivitySpeedResult? stravaParseWebActivitySpeed({
  required String activityId,
  required String pageHtml,
  String? streamsJson,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaParseWebActivitySpeed(
  activityId: activityId,
  pageHtml: pageHtml,
  streamsJson: streamsJson,
);

/// 同步预留一个远端读取 handle。底层复用上传操作注册表，使取消代际隔离规则完全一致。
StravaUploadReservation stravaReserveRemoteRead({
  required String operationId,
}) => WorkoutCoreRustLib.instance.api.crateApiSimpleStravaReserveRemoteRead(
  operationId: operationId,
);

/// 取消特定代际的远端读取，不会影响之后为同一 logical ID 新建的读取。
bool stravaCancelRemoteRead({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaCancelRemoteRead(
      operationHandle: operationHandle,
    );

/// 释放尚未启动的远端读取预留 handle；已启动任务由 RAII 自动释放。
bool stravaReleaseRemoteRead({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaReleaseRemoteRead(
      operationHandle: operationHandle,
    );

/// 同步预留一个不可重用 handle；Dart 必须先 reserve，再启动异步上传或轮询。
StravaUploadReservation stravaReserveUpload({required String operationId}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaReserveUpload(
      operationId: operationId,
    );

/// 精确取消同 generation handle。旧 handle 永远不能取消新一代同 logical ID 操作。
bool stravaCancelUpload({required String operationHandle}) => WorkoutCoreRustLib
    .instance
    .api
    .crateApiSimpleStravaCancelUpload(operationHandle: operationHandle);

/// 释放尚未启动的预留 handle；运行中的操作由 RAII 在 Future 结束时释放。
bool stravaReleaseUpload({required String operationHandle}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleStravaReleaseUpload(
      operationHandle: operationHandle,
    );

/// 预览使用异步工作线程；完整坐标摘要与有界显示数据分别计算。
Future<String> inspectFitPreview({required List<int> data}) =>
    WorkoutCoreRustLib.instance.api.crateApiSimpleInspectFitPreview(data: data);

/// Flutter 可传输的活动时间区间，供跨来源匹配使用。
class ActivityIntervalInput {
  final double startSeconds;
  final double endSeconds;
  final double durationSeconds;

  const ActivityIntervalInput({
    required this.startSeconds,
    required this.endSeconds,
    required this.durationSeconds,
  });

  @override
  int get hashCode =>
      startSeconds.hashCode ^ endSeconds.hashCode ^ durationSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActivityIntervalInput &&
          runtimeType == other.runtimeType &&
          startSeconds == other.startSeconds &&
          endSeconds == other.endSeconds &&
          durationSeconds == other.durationSeconds;
}

class FitProbeSummary {
  final int gpsPointCount;
  final int heartRatePointCount;
  final int qualityScore;

  const FitProbeSummary({
    required this.gpsPointCount,
    required this.heartRatePointCount,
    required this.qualityScore,
  });

  @override
  int get hashCode =>
      gpsPointCount.hashCode ^
      heartRatePointCount.hashCode ^
      qualityScore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FitProbeSummary &&
          runtimeType == other.runtimeType &&
          gpsPointCount == other.gpsPointCount &&
          heartRatePointCount == other.heartRatePointCount &&
          qualityScore == other.qualityScore;
}

/// 合并界面使用异步工作线程，避免在 UI 线程执行大型 FIT 解码。
class MergedFitResult {
  final Uint8List data;
  final Int32List offsetsSeconds;

  const MergedFitResult({required this.data, required this.offsetsSeconds});

  @override
  int get hashCode => data.hashCode ^ offsetsSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergedFitResult &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          offsetsSeconds == other.offsetsSeconds;
}

class OnelapLoginResult {
  final String token;
  final String uid;
  final String? refreshToken;

  const OnelapLoginResult({
    required this.token,
    required this.uid,
    this.refreshToken,
  });

  @override
  int get hashCode => token.hashCode ^ uid.hashCode ^ refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnelapLoginResult &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          uid == other.uid &&
          refreshToken == other.refreshToken;
}

/// Flutter 侧展示顽鹿活动列表所需字段；列表时间按调用方传入的 UTC 偏移解析。
class OnelapWorkoutResult {
  final String id;
  final String title;
  final String startTimeLocal;
  final double startTimeSeconds;
  final double endTimeSeconds;
  final double durationSeconds;
  final double? distanceMeters;

  const OnelapWorkoutResult({
    required this.id,
    required this.title,
    required this.startTimeLocal,
    required this.startTimeSeconds,
    required this.endTimeSeconds,
    required this.durationSeconds,
    this.distanceMeters,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startTimeLocal.hashCode ^
      startTimeSeconds.hashCode ^
      endTimeSeconds.hashCode ^
      durationSeconds.hashCode ^
      distanceMeters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnelapWorkoutResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startTimeLocal == other.startTimeLocal &&
          startTimeSeconds == other.startTimeSeconds &&
          endTimeSeconds == other.endTimeSeconds &&
          durationSeconds == other.durationSeconds &&
          distanceMeters == other.distanceMeters;
}

class PreparedFitResult {
  final Uint8List data;

  /// 按输入补源 FIT 顺序的实际字段计数、偏移与说明；无补源为 []。
  final String supplementReportsJson;
  final int repairedSpeedCount;
  final int rewrittenCoordinateCount;
  final double averageCoordinateDisplacementMeters;
  final int virtualPowerFilledCount;
  final bool powerSourceVirtual;
  final String? activityDescription;

  const PreparedFitResult({
    required this.data,
    required this.supplementReportsJson,
    required this.repairedSpeedCount,
    required this.rewrittenCoordinateCount,
    required this.averageCoordinateDisplacementMeters,
    required this.virtualPowerFilledCount,
    required this.powerSourceVirtual,
    this.activityDescription,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      supplementReportsJson.hashCode ^
      repairedSpeedCount.hashCode ^
      rewrittenCoordinateCount.hashCode ^
      averageCoordinateDisplacementMeters.hashCode ^
      virtualPowerFilledCount.hashCode ^
      powerSourceVirtual.hashCode ^
      activityDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreparedFitResult &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          supplementReportsJson == other.supplementReportsJson &&
          repairedSpeedCount == other.repairedSpeedCount &&
          rewrittenCoordinateCount == other.rewrittenCoordinateCount &&
          averageCoordinateDisplacementMeters ==
              other.averageCoordinateDisplacementMeters &&
          virtualPowerFilledCount == other.virtualPowerFilledCount &&
          powerSourceVirtual == other.powerSourceVirtual &&
          activityDescription == other.activityDescription;
}

/// Flutter 侧用于异常速度复查的官方活动摘要。
class StravaActivitySpeedResult {
  final String id;
  final String name;
  final double? startTimeSeconds;
  final String sportType;
  final double listedMaxSpeedMps;
  final double bestEffortPeakMps;
  final double maxSpeedMps;
  final double averageSpeedMps;

  const StravaActivitySpeedResult({
    required this.id,
    required this.name,
    this.startTimeSeconds,
    required this.sportType,
    required this.listedMaxSpeedMps,
    required this.bestEffortPeakMps,
    required this.maxSpeedMps,
    required this.averageSpeedMps,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      startTimeSeconds.hashCode ^
      sportType.hashCode ^
      listedMaxSpeedMps.hashCode ^
      bestEffortPeakMps.hashCode ^
      maxSpeedMps.hashCode ^
      averageSpeedMps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaActivitySpeedResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          startTimeSeconds == other.startTimeSeconds &&
          sportType == other.sportType &&
          listedMaxSpeedMps == other.listedMaxSpeedMps &&
          bestEffortPeakMps == other.bestEffortPeakMps &&
          maxSpeedMps == other.maxSpeedMps &&
          averageSpeedMps == other.averageSpeedMps;
}

class StravaRateLimitResult {
  final StravaRateLimitWindow overall;
  final StravaRateLimitWindow? read;
  final double observedAtUnixSeconds;
  final bool rateLimited;

  const StravaRateLimitResult({
    required this.overall,
    this.read,
    required this.observedAtUnixSeconds,
    required this.rateLimited,
  });

  @override
  int get hashCode =>
      overall.hashCode ^
      read.hashCode ^
      observedAtUnixSeconds.hashCode ^
      rateLimited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaRateLimitResult &&
          runtimeType == other.runtimeType &&
          overall == other.overall &&
          read == other.read &&
          observedAtUnixSeconds == other.observedAtUnixSeconds &&
          rateLimited == other.rateLimited;
}

class StravaRateLimitWindow {
  final int fifteenMinutesUsed;
  final int fifteenMinutesLimit;
  final int dailyUsed;
  final int dailyLimit;

  const StravaRateLimitWindow({
    required this.fifteenMinutesUsed,
    required this.fifteenMinutesLimit,
    required this.dailyUsed,
    required this.dailyLimit,
  });

  @override
  int get hashCode =>
      fifteenMinutesUsed.hashCode ^
      fifteenMinutesLimit.hashCode ^
      dailyUsed.hashCode ^
      dailyLimit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaRateLimitWindow &&
          runtimeType == other.runtimeType &&
          fifteenMinutesUsed == other.fifteenMinutesUsed &&
          fifteenMinutesLimit == other.fifteenMinutesLimit &&
          dailyUsed == other.dailyUsed &&
          dailyLimit == other.dailyLimit;
}

/// Flutter 侧用于上传前远端预检的活动区间；字段语义与旧 Swift `RemoteActivity` 一致。
class StravaRemoteActivityResult {
  final String id;
  final String? sportType;
  final double startTimeSeconds;
  final double endTimeSeconds;
  final double? distanceMeters;

  const StravaRemoteActivityResult({
    required this.id,
    this.sportType,
    required this.startTimeSeconds,
    required this.endTimeSeconds,
    this.distanceMeters,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sportType.hashCode ^
      startTimeSeconds.hashCode ^
      endTimeSeconds.hashCode ^
      distanceMeters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaRemoteActivityResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sportType == other.sportType &&
          startTimeSeconds == other.startTimeSeconds &&
          endTimeSeconds == other.endTimeSeconds &&
          distanceMeters == other.distanceMeters;
}

class StravaTokenResult {
  final String accessToken;
  final String refreshToken;
  final double expiresAt;

  const StravaTokenResult({
    required this.accessToken,
    required this.refreshToken,
    required this.expiresAt,
  });

  @override
  int get hashCode =>
      accessToken.hashCode ^ refreshToken.hashCode ^ expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaTokenResult &&
          runtimeType == other.runtimeType &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken &&
          expiresAt == other.expiresAt;
}

class StravaUploadFfiError {
  final StravaUploadFfiErrorCode code;
  final String message;

  const StravaUploadFfiError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaUploadFfiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

enum StravaUploadFfiErrorCode {
  invalidInput,
  operationInUse,
  clientBuild,
  transport,
  unauthorized,
  rateLimited,
  responseTooLarge,
  invalidResponse,
  uploadFailed,
  cancelled,
}

class StravaUploadFfiResponse {
  final StravaUploadFfiStatus status;
  final String? remoteId;
  final bool isDuplicate;
  final StravaUploadRetry? retry;
  final StravaUploadFfiError? error;

  const StravaUploadFfiResponse({
    required this.status,
    this.remoteId,
    required this.isDuplicate,
    this.retry,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      remoteId.hashCode ^
      isDuplicate.hashCode ^
      retry.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaUploadFfiResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          remoteId == other.remoteId &&
          isDuplicate == other.isDuplicate &&
          retry == other.retry &&
          error == other.error;
}

enum StravaUploadFfiStatus { completed, needsRefresh, failed, cancelled }

class StravaUploadReservation {
  final String handle;

  const StravaUploadReservation({required this.handle});

  @override
  int get hashCode => handle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaUploadReservation &&
          runtimeType == other.runtimeType &&
          handle == other.handle;
}

class StravaUploadRetry {
  final StravaUploadRetryStage stage;
  final String? uploadId;
  final int? pollAttempt;

  const StravaUploadRetry({
    required this.stage,
    this.uploadId,
    this.pollAttempt,
  });

  @override
  int get hashCode => stage.hashCode ^ uploadId.hashCode ^ pollAttempt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StravaUploadRetry &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          uploadId == other.uploadId &&
          pollAttempt == other.pollAttempt;
}

enum StravaUploadRetryStage { upload, poll }

class VirtualPowerFillInput {
  final bool includeInertia;
  final double riderMassKg;
  final double bikeMassKg;
  final double cda;

  const VirtualPowerFillInput({
    required this.includeInertia,
    required this.riderMassKg,
    required this.bikeMassKg,
    required this.cda,
  });

  @override
  int get hashCode =>
      includeInertia.hashCode ^
      riderMassKg.hashCode ^
      bikeMassKg.hashCode ^
      cda.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualPowerFillInput &&
          runtimeType == other.runtimeType &&
          includeInertia == other.includeInertia &&
          riderMassKg == other.riderMassKg &&
          bikeMassKg == other.bikeMassKg &&
          cda == other.cda;
}

class XingzheListReservation {
  final String handle;

  const XingzheListReservation({required this.handle});

  @override
  int get hashCode => handle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XingzheListReservation &&
          runtimeType == other.runtimeType &&
          handle == other.handle;
}

/// Flutter 侧展示行者活动列表所需字段；时间为 Unix 秒，区间按 `[from, to)` 过滤。
class XingzheWorkoutResult {
  final String id;
  final String title;
  final double startTimeSeconds;
  final double endTimeSeconds;
  final double durationSeconds;
  final double? distanceMeters;

  const XingzheWorkoutResult({
    required this.id,
    required this.title,
    required this.startTimeSeconds,
    required this.endTimeSeconds,
    required this.durationSeconds,
    this.distanceMeters,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startTimeSeconds.hashCode ^
      endTimeSeconds.hashCode ^
      durationSeconds.hashCode ^
      distanceMeters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XingzheWorkoutResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startTimeSeconds == other.startTimeSeconds &&
          endTimeSeconds == other.endTimeSeconds &&
          durationSeconds == other.durationSeconds &&
          distanceMeters == other.distanceMeters;
}
