// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1754669404;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__activity_match_score_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "activity_match_score",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_primary =
                <crate::api::simple::ActivityIntervalInput>::sse_decode(&mut deserializer);
            let api_candidate =
                <crate::api::simple::ActivityIntervalInput>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::activity_match_score(
                    api_primary,
                    api_candidate,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__best_activity_match_index_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "best_activity_match_index",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_primary =
                <crate::api::simple::ActivityIntervalInput>::sse_decode(&mut deserializer);
            let api_candidates =
                <Vec<crate::api::simple::ActivityIntervalInput>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::simple::best_activity_match_index(api_primary, api_candidates),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__encode_health_workout_fit_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encode_health_workout_fit",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bundle_json = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_timezone_offset_seconds = <i32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::simple::encode_health_workout_fit(
                        api_bundle_json,
                        api_timezone_offset_seconds,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__fit_content_summary_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fit_content_summary",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::fit_content_summary(api_data)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__is_commute_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_commute",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_distance_meters = <Option<f64>>::sse_decode(&mut deserializer);
            let api_duration_seconds = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::is_commute(
                    api_distance_meters,
                    api_duration_seconds,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__is_valid_fit_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "is_valid_fit",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::is_valid_fit(api_data))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__reencode_fit_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reencode_fit",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::reencode_fit(api_data)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__stable_dedupe_matches_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stable_dedupe_matches",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_start_a_seconds = <f64>::sse_decode(&mut deserializer);
            let api_distance_a_meters = <f64>::sse_decode(&mut deserializer);
            let api_start_b_seconds = <f64>::sse_decode(&mut deserializer);
            let api_distance_b_meters = <f64>::sse_decode(&mut deserializer);
            let api_duration_a_seconds = <Option<f64>>::sse_decode(&mut deserializer);
            let api_duration_b_seconds = <Option<f64>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::stable_dedupe_matches(
                    api_start_a_seconds,
                    api_distance_a_meters,
                    api_start_b_seconds,
                    api_distance_b_meters,
                    api_duration_a_seconds,
                    api_duration_b_seconds,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_cancel_remote_read_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_cancel_remote_read",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::simple::strava_cancel_remote_read(api_operation_handle),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_cancel_upload_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_cancel_upload",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::strava_cancel_upload(
                    api_operation_handle,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_exchange_code_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_exchange_code",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_client_id = <String>::sse_decode(&mut deserializer);
            let api_client_secret = <String>::sse_decode(&mut deserializer);
            let api_code = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::simple::strava_exchange_code(
                            api_client_id,
                            api_client_secret,
                            api_code,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_fetch_remote_activity_speed_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_fetch_remote_activity_speed",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_activity_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::simple::strava_fetch_remote_activity_speed(
                            api_operation_handle,
                            api_access_token,
                            api_activity_id,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_list_remote_activities_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_list_remote_activities",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_after_seconds = <i64>::sse_decode(&mut deserializer);
            let api_before_seconds = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::simple::strava_list_remote_activities(
                            api_operation_handle,
                            api_access_token,
                            api_after_seconds,
                            api_before_seconds,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_refresh_token_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_refresh_token",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_client_id = <String>::sse_decode(&mut deserializer);
            let api_client_secret = <String>::sse_decode(&mut deserializer);
            let api_refresh_token = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, String>(
                    (move || async move {
                        let output_ok = crate::api::simple::strava_refresh_token(
                            api_client_id,
                            api_client_secret,
                            api_refresh_token,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_release_remote_read_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_release_remote_read",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(
                    crate::api::simple::strava_release_remote_read(api_operation_handle),
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_release_upload_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_release_upload",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::strava_release_upload(
                    api_operation_handle,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_reserve_remote_read_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_reserve_remote_read",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::strava_reserve_remote_read(api_operation_id)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_reserve_upload_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_reserve_upload",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::strava_reserve_upload(api_operation_id)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__strava_resume_upload_poll_after_refresh_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_resume_upload_poll_after_refresh",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_upload_id = <String>::sse_decode(&mut deserializer);
            let api_poll_attempt = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::simple::strava_resume_upload_poll_after_refresh(
                                api_operation_handle,
                                api_access_token,
                                api_upload_id,
                                api_poll_attempt,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_retry_upload_after_refresh_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_retry_upload_after_refresh",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_fit = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_external_id = <String>::sse_decode(&mut deserializer);
            let api_filename = <String>::sse_decode(&mut deserializer);
            let api_commute = <bool>::sse_decode(&mut deserializer);
            let api_description = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::simple::strava_retry_upload_after_refresh(
                                api_operation_handle,
                                api_access_token,
                                api_fit,
                                api_external_id,
                                api_filename,
                                api_commute,
                                api_description,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__strava_upload_fit_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "strava_upload_fit",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_operation_handle = <String>::sse_decode(&mut deserializer);
            let api_access_token = <String>::sse_decode(&mut deserializer);
            let api_fit = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_external_id = <String>::sse_decode(&mut deserializer);
            let api_filename = <String>::sse_decode(&mut deserializer);
            let api_commute = <bool>::sse_decode(&mut deserializer);
            let api_description = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::api::simple::strava_upload_fit(
                                api_operation_handle,
                                api_access_token,
                                api_fit,
                                api_external_id,
                                api_filename,
                                api_commute,
                                api_description,
                            )
                            .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__simple__sync_fingerprint_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_fingerprint",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_primary_source_id = <String>::sse_decode(&mut deserializer);
            let api_primary_activity_id = <String>::sse_decode(&mut deserializer);
            let api_start_date_unix_seconds = <f64>::sse_decode(&mut deserializer);
            let api_supplement_source_ids = <Vec<String>>::sse_decode(&mut deserializer);
            let api_destination = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::sync_fingerprint(
                    api_primary_source_id,
                    api_primary_activity_id,
                    api_start_date_unix_seconds,
                    api_supplement_source_ids,
                    api_destination,
                )?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__sync_recovery_apply_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_recovery_apply",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_recovery_json = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_command_json = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api::simple::sync_recovery_apply(api_recovery_json, api_command_json)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__sync_recovery_reencode_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_recovery_reencode",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_recovery_json = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::simple::sync_recovery_reencode(api_recovery_json)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__sync_state_apply_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sync_state_apply",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_state_json = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_command_json = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok =
                    crate::api::simple::sync_state_apply(api_state_json, api_command_json)?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::simple::ActivityIntervalInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_startSeconds = <f64>::sse_decode(deserializer);
        let mut var_endSeconds = <f64>::sse_decode(deserializer);
        let mut var_durationSeconds = <f64>::sse_decode(deserializer);
        return crate::api::simple::ActivityIntervalInput {
            start_seconds: var_startSeconds,
            end_seconds: var_endSeconds,
            duration_seconds: var_durationSeconds,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::simple::FitProbeSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_gpsPointCount = <u32>::sse_decode(deserializer);
        let mut var_heartRatePointCount = <u32>::sse_decode(deserializer);
        let mut var_qualityScore = <u32>::sse_decode(deserializer);
        return crate::api::simple::FitProbeSummary {
            gps_point_count: var_gpsPointCount,
            heart_rate_point_count: var_heartRatePointCount,
            quality_score: var_qualityScore,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::ActivityIntervalInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::ActivityIntervalInput>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::simple::StravaRemoteActivityResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::simple::StravaRemoteActivityResult>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::simple::StravaActivitySpeedResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::simple::StravaActivitySpeedResult>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::simple::StravaUploadFfiError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::simple::StravaUploadFfiError>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::simple::StravaUploadRetry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::simple::StravaUploadRetry>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::simple::StravaActivitySpeedResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_startTimeSeconds = <Option<f64>>::sse_decode(deserializer);
        let mut var_sportType = <String>::sse_decode(deserializer);
        let mut var_listedMaxSpeedMps = <f64>::sse_decode(deserializer);
        let mut var_bestEffortPeakMps = <f64>::sse_decode(deserializer);
        let mut var_maxSpeedMps = <f64>::sse_decode(deserializer);
        let mut var_averageSpeedMps = <f64>::sse_decode(deserializer);
        return crate::api::simple::StravaActivitySpeedResult {
            id: var_id,
            name: var_name,
            start_time_seconds: var_startTimeSeconds,
            sport_type: var_sportType,
            listed_max_speed_mps: var_listedMaxSpeedMps,
            best_effort_peak_mps: var_bestEffortPeakMps,
            max_speed_mps: var_maxSpeedMps,
            average_speed_mps: var_averageSpeedMps,
        };
    }
}

impl SseDecode for crate::api::simple::StravaRemoteActivityResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_startTimeSeconds = <f64>::sse_decode(deserializer);
        let mut var_endTimeSeconds = <f64>::sse_decode(deserializer);
        let mut var_distanceMeters = <Option<f64>>::sse_decode(deserializer);
        return crate::api::simple::StravaRemoteActivityResult {
            id: var_id,
            start_time_seconds: var_startTimeSeconds,
            end_time_seconds: var_endTimeSeconds,
            distance_meters: var_distanceMeters,
        };
    }
}

impl SseDecode for crate::api::simple::StravaTokenResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_accessToken = <String>::sse_decode(deserializer);
        let mut var_refreshToken = <String>::sse_decode(deserializer);
        let mut var_expiresAt = <f64>::sse_decode(deserializer);
        return crate::api::simple::StravaTokenResult {
            access_token: var_accessToken,
            refresh_token: var_refreshToken,
            expires_at: var_expiresAt,
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadFfiError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_code = <crate::api::simple::StravaUploadFfiErrorCode>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::simple::StravaUploadFfiError {
            code: var_code,
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadFfiErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::StravaUploadFfiErrorCode::InvalidInput,
            1 => crate::api::simple::StravaUploadFfiErrorCode::OperationInUse,
            2 => crate::api::simple::StravaUploadFfiErrorCode::ClientBuild,
            3 => crate::api::simple::StravaUploadFfiErrorCode::Transport,
            4 => crate::api::simple::StravaUploadFfiErrorCode::Unauthorized,
            5 => crate::api::simple::StravaUploadFfiErrorCode::RateLimited,
            6 => crate::api::simple::StravaUploadFfiErrorCode::ResponseTooLarge,
            7 => crate::api::simple::StravaUploadFfiErrorCode::InvalidResponse,
            8 => crate::api::simple::StravaUploadFfiErrorCode::UploadFailed,
            9 => crate::api::simple::StravaUploadFfiErrorCode::Cancelled,
            _ => unreachable!("Invalid variant for StravaUploadFfiErrorCode: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadFfiResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_status = <crate::api::simple::StravaUploadFfiStatus>::sse_decode(deserializer);
        let mut var_remoteId = <Option<String>>::sse_decode(deserializer);
        let mut var_isDuplicate = <bool>::sse_decode(deserializer);
        let mut var_retry =
            <Option<crate::api::simple::StravaUploadRetry>>::sse_decode(deserializer);
        let mut var_error =
            <Option<crate::api::simple::StravaUploadFfiError>>::sse_decode(deserializer);
        return crate::api::simple::StravaUploadFfiResponse {
            status: var_status,
            remote_id: var_remoteId,
            is_duplicate: var_isDuplicate,
            retry: var_retry,
            error: var_error,
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadFfiStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::StravaUploadFfiStatus::Completed,
            1 => crate::api::simple::StravaUploadFfiStatus::NeedsRefresh,
            2 => crate::api::simple::StravaUploadFfiStatus::Failed,
            3 => crate::api::simple::StravaUploadFfiStatus::Cancelled,
            _ => unreachable!("Invalid variant for StravaUploadFfiStatus: {}", inner),
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadReservation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_handle = <String>::sse_decode(deserializer);
        return crate::api::simple::StravaUploadReservation { handle: var_handle };
    }
}

impl SseDecode for crate::api::simple::StravaUploadRetry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stage = <crate::api::simple::StravaUploadRetryStage>::sse_decode(deserializer);
        let mut var_uploadId = <Option<String>>::sse_decode(deserializer);
        let mut var_pollAttempt = <Option<u32>>::sse_decode(deserializer);
        return crate::api::simple::StravaUploadRetry {
            stage: var_stage,
            upload_id: var_uploadId,
            poll_attempt: var_pollAttempt,
        };
    }
}

impl SseDecode for crate::api::simple::StravaUploadRetryStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::simple::StravaUploadRetryStage::Upload,
            1 => crate::api::simple::StravaUploadRetryStage::Poll,
            _ => unreachable!("Invalid variant for StravaUploadRetryStage: {}", inner),
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__simple__encode_health_workout_fit_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        11 => {
            wire__crate__api__simple__strava_exchange_code_impl(port, ptr, rust_vec_len, data_len)
        }
        12 => wire__crate__api__simple__strava_fetch_remote_activity_speed_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api__simple__strava_list_remote_activities_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => {
            wire__crate__api__simple__strava_refresh_token_impl(port, ptr, rust_vec_len, data_len)
        }
        19 => wire__crate__api__simple__strava_resume_upload_poll_after_refresh_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        20 => wire__crate__api__simple__strava_retry_upload_after_refresh_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        21 => wire__crate__api__simple__strava_upload_fit_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__activity_match_score_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__simple__best_activity_match_index_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__simple__fit_content_summary_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__simple__is_commute_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__simple__is_valid_fit_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__simple__reencode_fit_impl(ptr, rust_vec_len, data_len),
        8 => wire__crate__api__simple__stable_dedupe_matches_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__simple__strava_cancel_remote_read_impl(ptr, rust_vec_len, data_len),
        10 => wire__crate__api__simple__strava_cancel_upload_impl(ptr, rust_vec_len, data_len),
        15 => {
            wire__crate__api__simple__strava_release_remote_read_impl(ptr, rust_vec_len, data_len)
        }
        16 => wire__crate__api__simple__strava_release_upload_impl(ptr, rust_vec_len, data_len),
        17 => {
            wire__crate__api__simple__strava_reserve_remote_read_impl(ptr, rust_vec_len, data_len)
        }
        18 => wire__crate__api__simple__strava_reserve_upload_impl(ptr, rust_vec_len, data_len),
        22 => wire__crate__api__simple__sync_fingerprint_impl(ptr, rust_vec_len, data_len),
        23 => wire__crate__api__simple__sync_recovery_apply_impl(ptr, rust_vec_len, data_len),
        24 => wire__crate__api__simple__sync_recovery_reencode_impl(ptr, rust_vec_len, data_len),
        25 => wire__crate__api__simple__sync_state_apply_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::ActivityIntervalInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.start_seconds.into_into_dart().into_dart(),
            self.end_seconds.into_into_dart().into_dart(),
            self.duration_seconds.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::ActivityIntervalInput
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::ActivityIntervalInput>
    for crate::api::simple::ActivityIntervalInput
{
    fn into_into_dart(self) -> crate::api::simple::ActivityIntervalInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::FitProbeSummary {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.gps_point_count.into_into_dart().into_dart(),
            self.heart_rate_point_count.into_into_dart().into_dart(),
            self.quality_score.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::FitProbeSummary
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::FitProbeSummary>
    for crate::api::simple::FitProbeSummary
{
    fn into_into_dart(self) -> crate::api::simple::FitProbeSummary {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaActivitySpeedResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.start_time_seconds.into_into_dart().into_dart(),
            self.sport_type.into_into_dart().into_dart(),
            self.listed_max_speed_mps.into_into_dart().into_dart(),
            self.best_effort_peak_mps.into_into_dart().into_dart(),
            self.max_speed_mps.into_into_dart().into_dart(),
            self.average_speed_mps.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaActivitySpeedResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaActivitySpeedResult>
    for crate::api::simple::StravaActivitySpeedResult
{
    fn into_into_dart(self) -> crate::api::simple::StravaActivitySpeedResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaRemoteActivityResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.start_time_seconds.into_into_dart().into_dart(),
            self.end_time_seconds.into_into_dart().into_dart(),
            self.distance_meters.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaRemoteActivityResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaRemoteActivityResult>
    for crate::api::simple::StravaRemoteActivityResult
{
    fn into_into_dart(self) -> crate::api::simple::StravaRemoteActivityResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaTokenResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.access_token.into_into_dart().into_dart(),
            self.refresh_token.into_into_dart().into_dart(),
            self.expires_at.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaTokenResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaTokenResult>
    for crate::api::simple::StravaTokenResult
{
    fn into_into_dart(self) -> crate::api::simple::StravaTokenResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadFfiError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.code.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadFfiError
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadFfiError>
    for crate::api::simple::StravaUploadFfiError
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadFfiError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadFfiErrorCode {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::InvalidInput => 0.into_dart(),
            Self::OperationInUse => 1.into_dart(),
            Self::ClientBuild => 2.into_dart(),
            Self::Transport => 3.into_dart(),
            Self::Unauthorized => 4.into_dart(),
            Self::RateLimited => 5.into_dart(),
            Self::ResponseTooLarge => 6.into_dart(),
            Self::InvalidResponse => 7.into_dart(),
            Self::UploadFailed => 8.into_dart(),
            Self::Cancelled => 9.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadFfiErrorCode
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadFfiErrorCode>
    for crate::api::simple::StravaUploadFfiErrorCode
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadFfiErrorCode {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadFfiResponse {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.status.into_into_dart().into_dart(),
            self.remote_id.into_into_dart().into_dart(),
            self.is_duplicate.into_into_dart().into_dart(),
            self.retry.into_into_dart().into_dart(),
            self.error.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadFfiResponse
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadFfiResponse>
    for crate::api::simple::StravaUploadFfiResponse
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadFfiResponse {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadFfiStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Completed => 0.into_dart(),
            Self::NeedsRefresh => 1.into_dart(),
            Self::Failed => 2.into_dart(),
            Self::Cancelled => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadFfiStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadFfiStatus>
    for crate::api::simple::StravaUploadFfiStatus
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadFfiStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadReservation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.handle.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadReservation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadReservation>
    for crate::api::simple::StravaUploadReservation
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadReservation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadRetry {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage.into_into_dart().into_dart(),
            self.upload_id.into_into_dart().into_dart(),
            self.poll_attempt.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadRetry
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadRetry>
    for crate::api::simple::StravaUploadRetry
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadRetry {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::simple::StravaUploadRetryStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Upload => 0.into_dart(),
            Self::Poll => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::simple::StravaUploadRetryStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::simple::StravaUploadRetryStage>
    for crate::api::simple::StravaUploadRetryStage
{
    fn into_into_dart(self) -> crate::api::simple::StravaUploadRetryStage {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::simple::ActivityIntervalInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.start_seconds, serializer);
        <f64>::sse_encode(self.end_seconds, serializer);
        <f64>::sse_encode(self.duration_seconds, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::simple::FitProbeSummary {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.gps_point_count, serializer);
        <u32>::sse_encode(self.heart_rate_point_count, serializer);
        <u32>::sse_encode(self.quality_score, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::ActivityIntervalInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::ActivityIntervalInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::simple::StravaRemoteActivityResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::simple::StravaRemoteActivityResult>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::simple::StravaActivitySpeedResult> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::simple::StravaActivitySpeedResult>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::simple::StravaUploadFfiError> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::simple::StravaUploadFfiError>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::simple::StravaUploadRetry> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::simple::StravaUploadRetry>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::simple::StravaActivitySpeedResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <Option<f64>>::sse_encode(self.start_time_seconds, serializer);
        <String>::sse_encode(self.sport_type, serializer);
        <f64>::sse_encode(self.listed_max_speed_mps, serializer);
        <f64>::sse_encode(self.best_effort_peak_mps, serializer);
        <f64>::sse_encode(self.max_speed_mps, serializer);
        <f64>::sse_encode(self.average_speed_mps, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaRemoteActivityResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <f64>::sse_encode(self.start_time_seconds, serializer);
        <f64>::sse_encode(self.end_time_seconds, serializer);
        <Option<f64>>::sse_encode(self.distance_meters, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaTokenResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.access_token, serializer);
        <String>::sse_encode(self.refresh_token, serializer);
        <f64>::sse_encode(self.expires_at, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaUploadFfiError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::simple::StravaUploadFfiErrorCode>::sse_encode(self.code, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaUploadFfiErrorCode {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::StravaUploadFfiErrorCode::InvalidInput => 0,
                crate::api::simple::StravaUploadFfiErrorCode::OperationInUse => 1,
                crate::api::simple::StravaUploadFfiErrorCode::ClientBuild => 2,
                crate::api::simple::StravaUploadFfiErrorCode::Transport => 3,
                crate::api::simple::StravaUploadFfiErrorCode::Unauthorized => 4,
                crate::api::simple::StravaUploadFfiErrorCode::RateLimited => 5,
                crate::api::simple::StravaUploadFfiErrorCode::ResponseTooLarge => 6,
                crate::api::simple::StravaUploadFfiErrorCode::InvalidResponse => 7,
                crate::api::simple::StravaUploadFfiErrorCode::UploadFailed => 8,
                crate::api::simple::StravaUploadFfiErrorCode::Cancelled => 9,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::StravaUploadFfiResponse {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::simple::StravaUploadFfiStatus>::sse_encode(self.status, serializer);
        <Option<String>>::sse_encode(self.remote_id, serializer);
        <bool>::sse_encode(self.is_duplicate, serializer);
        <Option<crate::api::simple::StravaUploadRetry>>::sse_encode(self.retry, serializer);
        <Option<crate::api::simple::StravaUploadFfiError>>::sse_encode(self.error, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaUploadFfiStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::StravaUploadFfiStatus::Completed => 0,
                crate::api::simple::StravaUploadFfiStatus::NeedsRefresh => 1,
                crate::api::simple::StravaUploadFfiStatus::Failed => 2,
                crate::api::simple::StravaUploadFfiStatus::Cancelled => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::simple::StravaUploadReservation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.handle, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaUploadRetry {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::simple::StravaUploadRetryStage>::sse_encode(self.stage, serializer);
        <Option<String>>::sse_encode(self.upload_id, serializer);
        <Option<u32>>::sse_encode(self.poll_attempt, serializer);
    }
}

impl SseEncode for crate::api::simple::StravaUploadRetryStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::simple::StravaUploadRetryStage::Upload => 0,
                crate::api::simple::StravaUploadRetryStage::Poll => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{Lifetimeable, Lockable, transform_result_dco};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
