// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class WorkoutCoreRustLibApiImplPlatform
    extends BaseApiImpl<WorkoutCoreRustLibWire> {
  WorkoutCoreRustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActivityIntervalInput dco_decode_activity_interval_input(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActivityIntervalInput dco_decode_box_autoadd_activity_interval_input(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  StravaActivitySpeedResult dco_decode_box_autoadd_strava_activity_speed_result(
    dynamic raw,
  );

  @protected
  StravaUploadFfiError dco_decode_box_autoadd_strava_upload_ffi_error(
    dynamic raw,
  );

  @protected
  StravaUploadRetry dco_decode_box_autoadd_strava_upload_retry(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FitProbeSummary dco_decode_fit_probe_summary(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActivityIntervalInput> dco_decode_list_activity_interval_input(
    dynamic raw,
  );

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<StravaRemoteActivityResult>
  dco_decode_list_strava_remote_activity_result(dynamic raw);

  @protected
  List<XingzheWorkoutResult> dco_decode_list_xingzhe_workout_result(
    dynamic raw,
  );

  @protected
  OnelapLoginResult dco_decode_onelap_login_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  StravaActivitySpeedResult?
  dco_decode_opt_box_autoadd_strava_activity_speed_result(dynamic raw);

  @protected
  StravaUploadFfiError? dco_decode_opt_box_autoadd_strava_upload_ffi_error(
    dynamic raw,
  );

  @protected
  StravaUploadRetry? dco_decode_opt_box_autoadd_strava_upload_retry(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  StravaActivitySpeedResult dco_decode_strava_activity_speed_result(
    dynamic raw,
  );

  @protected
  StravaRemoteActivityResult dco_decode_strava_remote_activity_result(
    dynamic raw,
  );

  @protected
  StravaTokenResult dco_decode_strava_token_result(dynamic raw);

  @protected
  StravaUploadFfiError dco_decode_strava_upload_ffi_error(dynamic raw);

  @protected
  StravaUploadFfiErrorCode dco_decode_strava_upload_ffi_error_code(dynamic raw);

  @protected
  StravaUploadFfiResponse dco_decode_strava_upload_ffi_response(dynamic raw);

  @protected
  StravaUploadFfiStatus dco_decode_strava_upload_ffi_status(dynamic raw);

  @protected
  StravaUploadReservation dco_decode_strava_upload_reservation(dynamic raw);

  @protected
  StravaUploadRetry dco_decode_strava_upload_retry(dynamic raw);

  @protected
  StravaUploadRetryStage dco_decode_strava_upload_retry_stage(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  XingzheListReservation dco_decode_xingzhe_list_reservation(dynamic raw);

  @protected
  XingzheWorkoutResult dco_decode_xingzhe_workout_result(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActivityIntervalInput sse_decode_activity_interval_input(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActivityIntervalInput sse_decode_box_autoadd_activity_interval_input(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  StravaActivitySpeedResult sse_decode_box_autoadd_strava_activity_speed_result(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiError sse_decode_box_autoadd_strava_upload_ffi_error(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadRetry sse_decode_box_autoadd_strava_upload_retry(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FitProbeSummary sse_decode_fit_probe_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActivityIntervalInput> sse_decode_list_activity_interval_input(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<StravaRemoteActivityResult>
  sse_decode_list_strava_remote_activity_result(SseDeserializer deserializer);

  @protected
  List<XingzheWorkoutResult> sse_decode_list_xingzhe_workout_result(
    SseDeserializer deserializer,
  );

  @protected
  OnelapLoginResult sse_decode_onelap_login_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  StravaActivitySpeedResult?
  sse_decode_opt_box_autoadd_strava_activity_speed_result(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiError? sse_decode_opt_box_autoadd_strava_upload_ffi_error(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadRetry? sse_decode_opt_box_autoadd_strava_upload_retry(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  StravaActivitySpeedResult sse_decode_strava_activity_speed_result(
    SseDeserializer deserializer,
  );

  @protected
  StravaRemoteActivityResult sse_decode_strava_remote_activity_result(
    SseDeserializer deserializer,
  );

  @protected
  StravaTokenResult sse_decode_strava_token_result(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiError sse_decode_strava_upload_ffi_error(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiErrorCode sse_decode_strava_upload_ffi_error_code(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiResponse sse_decode_strava_upload_ffi_response(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadFfiStatus sse_decode_strava_upload_ffi_status(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadReservation sse_decode_strava_upload_reservation(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadRetry sse_decode_strava_upload_retry(
    SseDeserializer deserializer,
  );

  @protected
  StravaUploadRetryStage sse_decode_strava_upload_retry_stage(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  XingzheListReservation sse_decode_xingzhe_list_reservation(
    SseDeserializer deserializer,
  );

  @protected
  XingzheWorkoutResult sse_decode_xingzhe_workout_result(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_activity_interval_input(
    ActivityIntervalInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_activity_interval_input(
    ActivityIntervalInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_strava_activity_speed_result(
    StravaActivitySpeedResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_strava_upload_ffi_error(
    StravaUploadFfiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_strava_upload_retry(
    StravaUploadRetry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fit_probe_summary(
    FitProbeSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_activity_interval_input(
    List<ActivityIntervalInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_strava_remote_activity_result(
    List<StravaRemoteActivityResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_xingzhe_workout_result(
    List<XingzheWorkoutResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onelap_login_result(
    OnelapLoginResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_strava_activity_speed_result(
    StravaActivitySpeedResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_strava_upload_ffi_error(
    StravaUploadFfiError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_strava_upload_retry(
    StravaUploadRetry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_strava_activity_speed_result(
    StravaActivitySpeedResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_remote_activity_result(
    StravaRemoteActivityResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_token_result(
    StravaTokenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_ffi_error(
    StravaUploadFfiError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_ffi_error_code(
    StravaUploadFfiErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_ffi_response(
    StravaUploadFfiResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_ffi_status(
    StravaUploadFfiStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_reservation(
    StravaUploadReservation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_retry(
    StravaUploadRetry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_strava_upload_retry_stage(
    StravaUploadRetryStage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_xingzhe_list_reservation(
    XingzheListReservation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_xingzhe_workout_result(
    XingzheWorkoutResult self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class WorkoutCoreRustLibWire implements BaseWire {
  WorkoutCoreRustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external WorkoutCoreRustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type WorkoutCoreRustLibWasmModule._(JSObject _) implements JSObject {}
