// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class WorkoutCoreRustLib
    extends
        BaseEntrypoint<
          WorkoutCoreRustLibApi,
          WorkoutCoreRustLibApiImpl,
          WorkoutCoreRustLibWire
        > {
  @internal
  static final instance = WorkoutCoreRustLib._();

  WorkoutCoreRustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    WorkoutCoreRustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required WorkoutCoreRustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<WorkoutCoreRustLibApiImpl, WorkoutCoreRustLibWire>
  get apiImplConstructor => WorkoutCoreRustLibApiImpl.new;

  @override
  WireConstructor<WorkoutCoreRustLibWire> get wireConstructor =>
      WorkoutCoreRustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1754669404;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_health_workout_export',
        ioDirectory: '../rust/workout_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class WorkoutCoreRustLibApi extends BaseApi {
  double? crateApiSimpleActivityMatchScore({
    required ActivityIntervalInput primary,
    required ActivityIntervalInput candidate,
  });

  int? crateApiSimpleBestActivityMatchIndex({
    required ActivityIntervalInput primary,
    required List<ActivityIntervalInput> candidates,
  });

  Future<Uint8List> crateApiSimpleEncodeHealthWorkoutFit({
    required List<int> bundleJson,
    required int timezoneOffsetSeconds,
  });

  FitProbeSummary crateApiSimpleFitContentSummary({required List<int> data});

  bool crateApiSimpleIsCommute({
    double? distanceMeters,
    required double durationSeconds,
  });

  bool crateApiSimpleIsValidFit({required List<int> data});

  Uint8List crateApiSimpleReencodeFit({required List<int> data});

  bool crateApiSimpleStableDedupeMatches({
    required double startASeconds,
    required double distanceAMeters,
    required double startBSeconds,
    required double distanceBMeters,
    double? durationASeconds,
    double? durationBSeconds,
  });

  bool crateApiSimpleStravaCancelRemoteRead({required String operationHandle});

  bool crateApiSimpleStravaCancelUpload({required String operationHandle});

  Future<StravaTokenResult> crateApiSimpleStravaExchangeCode({
    required String clientId,
    required String clientSecret,
    required String code,
  });

  Future<StravaActivitySpeedResult?>
  crateApiSimpleStravaFetchRemoteActivitySpeed({
    required String operationHandle,
    required String accessToken,
    required String activityId,
  });

  Future<List<StravaRemoteActivityResult>>
  crateApiSimpleStravaListRemoteActivities({
    required String operationHandle,
    required String accessToken,
    required PlatformInt64 afterSeconds,
    required PlatformInt64 beforeSeconds,
  });

  Future<StravaTokenResult> crateApiSimpleStravaRefreshToken({
    required String clientId,
    required String clientSecret,
    required String refreshToken,
  });

  bool crateApiSimpleStravaReleaseRemoteRead({required String operationHandle});

  bool crateApiSimpleStravaReleaseUpload({required String operationHandle});

  StravaUploadReservation crateApiSimpleStravaReserveRemoteRead({
    required String operationId,
  });

  StravaUploadReservation crateApiSimpleStravaReserveUpload({
    required String operationId,
  });

  Future<StravaUploadFfiResponse>
  crateApiSimpleStravaResumeUploadPollAfterRefresh({
    required String operationHandle,
    required String accessToken,
    required String uploadId,
    required int pollAttempt,
  });

  Future<StravaUploadFfiResponse> crateApiSimpleStravaRetryUploadAfterRefresh({
    required String operationHandle,
    required String accessToken,
    required List<int> fit,
    required String externalId,
    required String filename,
    required bool commute,
    String? description,
  });

  Future<StravaUploadFfiResponse> crateApiSimpleStravaUploadFit({
    required String operationHandle,
    required String accessToken,
    required List<int> fit,
    required String externalId,
    required String filename,
    required bool commute,
    String? description,
  });

  String crateApiSimpleSyncFingerprint({
    required String primarySourceId,
    required String primaryActivityId,
    required double startDateUnixSeconds,
    required List<String> supplementSourceIds,
    required String destination,
  });

  Uint8List crateApiSimpleSyncRecoveryApply({
    required List<int> recoveryJson,
    required List<int> commandJson,
  });

  Uint8List crateApiSimpleSyncRecoveryReencode({
    required List<int> recoveryJson,
  });

  Uint8List crateApiSimpleSyncStateApply({
    required List<int> stateJson,
    required List<int> commandJson,
  });
}

class WorkoutCoreRustLibApiImpl extends WorkoutCoreRustLibApiImplPlatform
    implements WorkoutCoreRustLibApi {
  WorkoutCoreRustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  double? crateApiSimpleActivityMatchScore({
    required ActivityIntervalInput primary,
    required ActivityIntervalInput candidate,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_activity_interval_input(primary, serializer);
          sse_encode_box_autoadd_activity_interval_input(candidate, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleActivityMatchScoreConstMeta,
        argValues: [primary, candidate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleActivityMatchScoreConstMeta =>
      const TaskConstMeta(
        debugName: "activity_match_score",
        argNames: ["primary", "candidate"],
      );

  @override
  int? crateApiSimpleBestActivityMatchIndex({
    required ActivityIntervalInput primary,
    required List<ActivityIntervalInput> candidates,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_activity_interval_input(primary, serializer);
          sse_encode_list_activity_interval_input(candidates, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleBestActivityMatchIndexConstMeta,
        argValues: [primary, candidates],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleBestActivityMatchIndexConstMeta =>
      const TaskConstMeta(
        debugName: "best_activity_match_index",
        argNames: ["primary", "candidates"],
      );

  @override
  Future<Uint8List> crateApiSimpleEncodeHealthWorkoutFit({
    required List<int> bundleJson,
    required int timezoneOffsetSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bundleJson, serializer);
          sse_encode_i_32(timezoneOffsetSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncodeHealthWorkoutFitConstMeta,
        argValues: [bundleJson, timezoneOffsetSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeHealthWorkoutFitConstMeta =>
      const TaskConstMeta(
        debugName: "encode_health_workout_fit",
        argNames: ["bundleJson", "timezoneOffsetSeconds"],
      );

  @override
  FitProbeSummary crateApiSimpleFitContentSummary({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fit_probe_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleFitContentSummaryConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleFitContentSummaryConstMeta =>
      const TaskConstMeta(debugName: "fit_content_summary", argNames: ["data"]);

  @override
  bool crateApiSimpleIsCommute({
    double? distanceMeters,
    required double durationSeconds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_f_64(distanceMeters, serializer);
          sse_encode_f_64(durationSeconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsCommuteConstMeta,
        argValues: [distanceMeters, durationSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsCommuteConstMeta => const TaskConstMeta(
    debugName: "is_commute",
    argNames: ["distanceMeters", "durationSeconds"],
  );

  @override
  bool crateApiSimpleIsValidFit({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleIsValidFitConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleIsValidFitConstMeta =>
      const TaskConstMeta(debugName: "is_valid_fit", argNames: ["data"]);

  @override
  Uint8List crateApiSimpleReencodeFit({required List<int> data}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleReencodeFitConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleReencodeFitConstMeta =>
      const TaskConstMeta(debugName: "reencode_fit", argNames: ["data"]);

  @override
  bool crateApiSimpleStableDedupeMatches({
    required double startASeconds,
    required double distanceAMeters,
    required double startBSeconds,
    required double distanceBMeters,
    double? durationASeconds,
    double? durationBSeconds,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(startASeconds, serializer);
          sse_encode_f_64(distanceAMeters, serializer);
          sse_encode_f_64(startBSeconds, serializer);
          sse_encode_f_64(distanceBMeters, serializer);
          sse_encode_opt_box_autoadd_f_64(durationASeconds, serializer);
          sse_encode_opt_box_autoadd_f_64(durationBSeconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStableDedupeMatchesConstMeta,
        argValues: [
          startASeconds,
          distanceAMeters,
          startBSeconds,
          distanceBMeters,
          durationASeconds,
          durationBSeconds,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStableDedupeMatchesConstMeta =>
      const TaskConstMeta(
        debugName: "stable_dedupe_matches",
        argNames: [
          "startASeconds",
          "distanceAMeters",
          "startBSeconds",
          "distanceBMeters",
          "durationASeconds",
          "durationBSeconds",
        ],
      );

  @override
  bool crateApiSimpleStravaCancelRemoteRead({required String operationHandle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaCancelRemoteReadConstMeta,
        argValues: [operationHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaCancelRemoteReadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_cancel_remote_read",
        argNames: ["operationHandle"],
      );

  @override
  bool crateApiSimpleStravaCancelUpload({required String operationHandle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaCancelUploadConstMeta,
        argValues: [operationHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaCancelUploadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_cancel_upload",
        argNames: ["operationHandle"],
      );

  @override
  Future<StravaTokenResult> crateApiSimpleStravaExchangeCode({
    required String clientId,
    required String clientSecret,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(clientId, serializer);
          sse_encode_String(clientSecret, serializer);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_token_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaExchangeCodeConstMeta,
        argValues: [clientId, clientSecret, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaExchangeCodeConstMeta =>
      const TaskConstMeta(
        debugName: "strava_exchange_code",
        argNames: ["clientId", "clientSecret", "code"],
      );

  @override
  Future<StravaActivitySpeedResult?>
  crateApiSimpleStravaFetchRemoteActivitySpeed({
    required String operationHandle,
    required String accessToken,
    required String activityId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(activityId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_strava_activity_speed_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaFetchRemoteActivitySpeedConstMeta,
        argValues: [operationHandle, accessToken, activityId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaFetchRemoteActivitySpeedConstMeta =>
      const TaskConstMeta(
        debugName: "strava_fetch_remote_activity_speed",
        argNames: ["operationHandle", "accessToken", "activityId"],
      );

  @override
  Future<List<StravaRemoteActivityResult>>
  crateApiSimpleStravaListRemoteActivities({
    required String operationHandle,
    required String accessToken,
    required PlatformInt64 afterSeconds,
    required PlatformInt64 beforeSeconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_i_64(afterSeconds, serializer);
          sse_encode_i_64(beforeSeconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_strava_remote_activity_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaListRemoteActivitiesConstMeta,
        argValues: [operationHandle, accessToken, afterSeconds, beforeSeconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaListRemoteActivitiesConstMeta =>
      const TaskConstMeta(
        debugName: "strava_list_remote_activities",
        argNames: [
          "operationHandle",
          "accessToken",
          "afterSeconds",
          "beforeSeconds",
        ],
      );

  @override
  Future<StravaTokenResult> crateApiSimpleStravaRefreshToken({
    required String clientId,
    required String clientSecret,
    required String refreshToken,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(clientId, serializer);
          sse_encode_String(clientSecret, serializer);
          sse_encode_String(refreshToken, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_token_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaRefreshTokenConstMeta,
        argValues: [clientId, clientSecret, refreshToken],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaRefreshTokenConstMeta =>
      const TaskConstMeta(
        debugName: "strava_refresh_token",
        argNames: ["clientId", "clientSecret", "refreshToken"],
      );

  @override
  bool crateApiSimpleStravaReleaseRemoteRead({
    required String operationHandle,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaReleaseRemoteReadConstMeta,
        argValues: [operationHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaReleaseRemoteReadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_release_remote_read",
        argNames: ["operationHandle"],
      );

  @override
  bool crateApiSimpleStravaReleaseUpload({required String operationHandle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaReleaseUploadConstMeta,
        argValues: [operationHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaReleaseUploadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_release_upload",
        argNames: ["operationHandle"],
      );

  @override
  StravaUploadReservation crateApiSimpleStravaReserveRemoteRead({
    required String operationId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_upload_reservation,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaReserveRemoteReadConstMeta,
        argValues: [operationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaReserveRemoteReadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_reserve_remote_read",
        argNames: ["operationId"],
      );

  @override
  StravaUploadReservation crateApiSimpleStravaReserveUpload({
    required String operationId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_upload_reservation,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleStravaReserveUploadConstMeta,
        argValues: [operationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaReserveUploadConstMeta =>
      const TaskConstMeta(
        debugName: "strava_reserve_upload",
        argNames: ["operationId"],
      );

  @override
  Future<StravaUploadFfiResponse>
  crateApiSimpleStravaResumeUploadPollAfterRefresh({
    required String operationHandle,
    required String accessToken,
    required String uploadId,
    required int pollAttempt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_String(uploadId, serializer);
          sse_encode_u_32(pollAttempt, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_upload_ffi_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaResumeUploadPollAfterRefreshConstMeta,
        argValues: [operationHandle, accessToken, uploadId, pollAttempt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleStravaResumeUploadPollAfterRefreshConstMeta =>
      const TaskConstMeta(
        debugName: "strava_resume_upload_poll_after_refresh",
        argNames: ["operationHandle", "accessToken", "uploadId", "pollAttempt"],
      );

  @override
  Future<StravaUploadFfiResponse> crateApiSimpleStravaRetryUploadAfterRefresh({
    required String operationHandle,
    required String accessToken,
    required List<int> fit,
    required String externalId,
    required String filename,
    required bool commute,
    String? description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_list_prim_u_8_loose(fit, serializer);
          sse_encode_String(externalId, serializer);
          sse_encode_String(filename, serializer);
          sse_encode_bool(commute, serializer);
          sse_encode_opt_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_upload_ffi_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaRetryUploadAfterRefreshConstMeta,
        argValues: [
          operationHandle,
          accessToken,
          fit,
          externalId,
          filename,
          commute,
          description,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaRetryUploadAfterRefreshConstMeta =>
      const TaskConstMeta(
        debugName: "strava_retry_upload_after_refresh",
        argNames: [
          "operationHandle",
          "accessToken",
          "fit",
          "externalId",
          "filename",
          "commute",
          "description",
        ],
      );

  @override
  Future<StravaUploadFfiResponse> crateApiSimpleStravaUploadFit({
    required String operationHandle,
    required String accessToken,
    required List<int> fit,
    required String externalId,
    required String filename,
    required bool commute,
    String? description,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(operationHandle, serializer);
          sse_encode_String(accessToken, serializer);
          sse_encode_list_prim_u_8_loose(fit, serializer);
          sse_encode_String(externalId, serializer);
          sse_encode_String(filename, serializer);
          sse_encode_bool(commute, serializer);
          sse_encode_opt_String(description, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_strava_upload_ffi_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleStravaUploadFitConstMeta,
        argValues: [
          operationHandle,
          accessToken,
          fit,
          externalId,
          filename,
          commute,
          description,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleStravaUploadFitConstMeta =>
      const TaskConstMeta(
        debugName: "strava_upload_fit",
        argNames: [
          "operationHandle",
          "accessToken",
          "fit",
          "externalId",
          "filename",
          "commute",
          "description",
        ],
      );

  @override
  String crateApiSimpleSyncFingerprint({
    required String primarySourceId,
    required String primaryActivityId,
    required double startDateUnixSeconds,
    required List<String> supplementSourceIds,
    required String destination,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(primarySourceId, serializer);
          sse_encode_String(primaryActivityId, serializer);
          sse_encode_f_64(startDateUnixSeconds, serializer);
          sse_encode_list_String(supplementSourceIds, serializer);
          sse_encode_String(destination, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSyncFingerprintConstMeta,
        argValues: [
          primarySourceId,
          primaryActivityId,
          startDateUnixSeconds,
          supplementSourceIds,
          destination,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "sync_fingerprint",
        argNames: [
          "primarySourceId",
          "primaryActivityId",
          "startDateUnixSeconds",
          "supplementSourceIds",
          "destination",
        ],
      );

  @override
  Uint8List crateApiSimpleSyncRecoveryApply({
    required List<int> recoveryJson,
    required List<int> commandJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(recoveryJson, serializer);
          sse_encode_list_prim_u_8_loose(commandJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSyncRecoveryApplyConstMeta,
        argValues: [recoveryJson, commandJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncRecoveryApplyConstMeta =>
      const TaskConstMeta(
        debugName: "sync_recovery_apply",
        argNames: ["recoveryJson", "commandJson"],
      );

  @override
  Uint8List crateApiSimpleSyncRecoveryReencode({
    required List<int> recoveryJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(recoveryJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSyncRecoveryReencodeConstMeta,
        argValues: [recoveryJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncRecoveryReencodeConstMeta =>
      const TaskConstMeta(
        debugName: "sync_recovery_reencode",
        argNames: ["recoveryJson"],
      );

  @override
  Uint8List crateApiSimpleSyncStateApply({
    required List<int> stateJson,
    required List<int> commandJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(stateJson, serializer);
          sse_encode_list_prim_u_8_loose(commandJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSyncStateApplyConstMeta,
        argValues: [stateJson, commandJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncStateApplyConstMeta =>
      const TaskConstMeta(
        debugName: "sync_state_apply",
        argNames: ["stateJson", "commandJson"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActivityIntervalInput dco_decode_activity_interval_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ActivityIntervalInput(
      startSeconds: dco_decode_f_64(arr[0]),
      endSeconds: dco_decode_f_64(arr[1]),
      durationSeconds: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ActivityIntervalInput dco_decode_box_autoadd_activity_interval_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_activity_interval_input(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  StravaActivitySpeedResult dco_decode_box_autoadd_strava_activity_speed_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_strava_activity_speed_result(raw);
  }

  @protected
  StravaUploadFfiError dco_decode_box_autoadd_strava_upload_ffi_error(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_strava_upload_ffi_error(raw);
  }

  @protected
  StravaUploadRetry dco_decode_box_autoadd_strava_upload_retry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_strava_upload_retry(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FitProbeSummary dco_decode_fit_probe_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FitProbeSummary(
      gpsPointCount: dco_decode_u_32(arr[0]),
      heartRatePointCount: dco_decode_u_32(arr[1]),
      qualityScore: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ActivityIntervalInput> dco_decode_list_activity_interval_input(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_activity_interval_input)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StravaRemoteActivityResult>
  dco_decode_list_strava_remote_activity_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_strava_remote_activity_result)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  StravaActivitySpeedResult?
  dco_decode_opt_box_autoadd_strava_activity_speed_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_strava_activity_speed_result(raw);
  }

  @protected
  StravaUploadFfiError? dco_decode_opt_box_autoadd_strava_upload_ffi_error(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_strava_upload_ffi_error(raw);
  }

  @protected
  StravaUploadRetry? dco_decode_opt_box_autoadd_strava_upload_retry(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_strava_upload_retry(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  StravaActivitySpeedResult dco_decode_strava_activity_speed_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return StravaActivitySpeedResult(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      startTimeSeconds: dco_decode_opt_box_autoadd_f_64(arr[2]),
      sportType: dco_decode_String(arr[3]),
      listedMaxSpeedMps: dco_decode_f_64(arr[4]),
      bestEffortPeakMps: dco_decode_f_64(arr[5]),
      maxSpeedMps: dco_decode_f_64(arr[6]),
      averageSpeedMps: dco_decode_f_64(arr[7]),
    );
  }

  @protected
  StravaRemoteActivityResult dco_decode_strava_remote_activity_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StravaRemoteActivityResult(
      id: dco_decode_String(arr[0]),
      startTimeSeconds: dco_decode_f_64(arr[1]),
      endTimeSeconds: dco_decode_f_64(arr[2]),
      distanceMeters: dco_decode_opt_box_autoadd_f_64(arr[3]),
    );
  }

  @protected
  StravaTokenResult dco_decode_strava_token_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StravaTokenResult(
      accessToken: dco_decode_String(arr[0]),
      refreshToken: dco_decode_String(arr[1]),
      expiresAt: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  StravaUploadFfiError dco_decode_strava_upload_ffi_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StravaUploadFfiError(
      code: dco_decode_strava_upload_ffi_error_code(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  StravaUploadFfiErrorCode dco_decode_strava_upload_ffi_error_code(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StravaUploadFfiErrorCode.values[raw as int];
  }

  @protected
  StravaUploadFfiResponse dco_decode_strava_upload_ffi_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StravaUploadFfiResponse(
      status: dco_decode_strava_upload_ffi_status(arr[0]),
      remoteId: dco_decode_opt_String(arr[1]),
      isDuplicate: dco_decode_bool(arr[2]),
      retry: dco_decode_opt_box_autoadd_strava_upload_retry(arr[3]),
      error: dco_decode_opt_box_autoadd_strava_upload_ffi_error(arr[4]),
    );
  }

  @protected
  StravaUploadFfiStatus dco_decode_strava_upload_ffi_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StravaUploadFfiStatus.values[raw as int];
  }

  @protected
  StravaUploadReservation dco_decode_strava_upload_reservation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return StravaUploadReservation(handle: dco_decode_String(arr[0]));
  }

  @protected
  StravaUploadRetry dco_decode_strava_upload_retry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StravaUploadRetry(
      stage: dco_decode_strava_upload_retry_stage(arr[0]),
      uploadId: dco_decode_opt_String(arr[1]),
      pollAttempt: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  StravaUploadRetryStage dco_decode_strava_upload_retry_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StravaUploadRetryStage.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActivityIntervalInput sse_decode_activity_interval_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startSeconds = sse_decode_f_64(deserializer);
    var var_endSeconds = sse_decode_f_64(deserializer);
    var var_durationSeconds = sse_decode_f_64(deserializer);
    return ActivityIntervalInput(
      startSeconds: var_startSeconds,
      endSeconds: var_endSeconds,
      durationSeconds: var_durationSeconds,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ActivityIntervalInput sse_decode_box_autoadd_activity_interval_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_activity_interval_input(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  StravaActivitySpeedResult sse_decode_box_autoadd_strava_activity_speed_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_strava_activity_speed_result(deserializer));
  }

  @protected
  StravaUploadFfiError sse_decode_box_autoadd_strava_upload_ffi_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_strava_upload_ffi_error(deserializer));
  }

  @protected
  StravaUploadRetry sse_decode_box_autoadd_strava_upload_retry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_strava_upload_retry(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FitProbeSummary sse_decode_fit_probe_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gpsPointCount = sse_decode_u_32(deserializer);
    var var_heartRatePointCount = sse_decode_u_32(deserializer);
    var var_qualityScore = sse_decode_u_32(deserializer);
    return FitProbeSummary(
      gpsPointCount: var_gpsPointCount,
      heartRatePointCount: var_heartRatePointCount,
      qualityScore: var_qualityScore,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ActivityIntervalInput> sse_decode_list_activity_interval_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActivityIntervalInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_activity_interval_input(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StravaRemoteActivityResult>
  sse_decode_list_strava_remote_activity_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StravaRemoteActivityResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_strava_remote_activity_result(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StravaActivitySpeedResult?
  sse_decode_opt_box_autoadd_strava_activity_speed_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_strava_activity_speed_result(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  StravaUploadFfiError? sse_decode_opt_box_autoadd_strava_upload_ffi_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_strava_upload_ffi_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StravaUploadRetry? sse_decode_opt_box_autoadd_strava_upload_retry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_strava_upload_retry(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StravaActivitySpeedResult sse_decode_strava_activity_speed_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_startTimeSeconds = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_sportType = sse_decode_String(deserializer);
    var var_listedMaxSpeedMps = sse_decode_f_64(deserializer);
    var var_bestEffortPeakMps = sse_decode_f_64(deserializer);
    var var_maxSpeedMps = sse_decode_f_64(deserializer);
    var var_averageSpeedMps = sse_decode_f_64(deserializer);
    return StravaActivitySpeedResult(
      id: var_id,
      name: var_name,
      startTimeSeconds: var_startTimeSeconds,
      sportType: var_sportType,
      listedMaxSpeedMps: var_listedMaxSpeedMps,
      bestEffortPeakMps: var_bestEffortPeakMps,
      maxSpeedMps: var_maxSpeedMps,
      averageSpeedMps: var_averageSpeedMps,
    );
  }

  @protected
  StravaRemoteActivityResult sse_decode_strava_remote_activity_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_startTimeSeconds = sse_decode_f_64(deserializer);
    var var_endTimeSeconds = sse_decode_f_64(deserializer);
    var var_distanceMeters = sse_decode_opt_box_autoadd_f_64(deserializer);
    return StravaRemoteActivityResult(
      id: var_id,
      startTimeSeconds: var_startTimeSeconds,
      endTimeSeconds: var_endTimeSeconds,
      distanceMeters: var_distanceMeters,
    );
  }

  @protected
  StravaTokenResult sse_decode_strava_token_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    var var_expiresAt = sse_decode_f_64(deserializer);
    return StravaTokenResult(
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
      expiresAt: var_expiresAt,
    );
  }

  @protected
  StravaUploadFfiError sse_decode_strava_upload_ffi_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_strava_upload_ffi_error_code(deserializer);
    var var_message = sse_decode_String(deserializer);
    return StravaUploadFfiError(code: var_code, message: var_message);
  }

  @protected
  StravaUploadFfiErrorCode sse_decode_strava_upload_ffi_error_code(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StravaUploadFfiErrorCode.values[inner];
  }

  @protected
  StravaUploadFfiResponse sse_decode_strava_upload_ffi_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_strava_upload_ffi_status(deserializer);
    var var_remoteId = sse_decode_opt_String(deserializer);
    var var_isDuplicate = sse_decode_bool(deserializer);
    var var_retry = sse_decode_opt_box_autoadd_strava_upload_retry(
      deserializer,
    );
    var var_error = sse_decode_opt_box_autoadd_strava_upload_ffi_error(
      deserializer,
    );
    return StravaUploadFfiResponse(
      status: var_status,
      remoteId: var_remoteId,
      isDuplicate: var_isDuplicate,
      retry: var_retry,
      error: var_error,
    );
  }

  @protected
  StravaUploadFfiStatus sse_decode_strava_upload_ffi_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StravaUploadFfiStatus.values[inner];
  }

  @protected
  StravaUploadReservation sse_decode_strava_upload_reservation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_String(deserializer);
    return StravaUploadReservation(handle: var_handle);
  }

  @protected
  StravaUploadRetry sse_decode_strava_upload_retry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_stage = sse_decode_strava_upload_retry_stage(deserializer);
    var var_uploadId = sse_decode_opt_String(deserializer);
    var var_pollAttempt = sse_decode_opt_box_autoadd_u_32(deserializer);
    return StravaUploadRetry(
      stage: var_stage,
      uploadId: var_uploadId,
      pollAttempt: var_pollAttempt,
    );
  }

  @protected
  StravaUploadRetryStage sse_decode_strava_upload_retry_stage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StravaUploadRetryStage.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_activity_interval_input(
    ActivityIntervalInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.startSeconds, serializer);
    sse_encode_f_64(self.endSeconds, serializer);
    sse_encode_f_64(self.durationSeconds, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_activity_interval_input(
    ActivityIntervalInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_activity_interval_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_strava_activity_speed_result(
    StravaActivitySpeedResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_activity_speed_result(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_strava_upload_ffi_error(
    StravaUploadFfiError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_upload_ffi_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_strava_upload_retry(
    StravaUploadRetry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_upload_retry(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fit_probe_summary(
    FitProbeSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.gpsPointCount, serializer);
    sse_encode_u_32(self.heartRatePointCount, serializer);
    sse_encode_u_32(self.qualityScore, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_activity_interval_input(
    List<ActivityIntervalInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_activity_interval_input(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_strava_remote_activity_result(
    List<StravaRemoteActivityResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_strava_remote_activity_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_strava_activity_speed_result(
    StravaActivitySpeedResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_strava_activity_speed_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_strava_upload_ffi_error(
    StravaUploadFfiError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_strava_upload_ffi_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_strava_upload_retry(
    StravaUploadRetry? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_strava_upload_retry(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_strava_activity_speed_result(
    StravaActivitySpeedResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_f_64(self.startTimeSeconds, serializer);
    sse_encode_String(self.sportType, serializer);
    sse_encode_f_64(self.listedMaxSpeedMps, serializer);
    sse_encode_f_64(self.bestEffortPeakMps, serializer);
    sse_encode_f_64(self.maxSpeedMps, serializer);
    sse_encode_f_64(self.averageSpeedMps, serializer);
  }

  @protected
  void sse_encode_strava_remote_activity_result(
    StravaRemoteActivityResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_f_64(self.startTimeSeconds, serializer);
    sse_encode_f_64(self.endTimeSeconds, serializer);
    sse_encode_opt_box_autoadd_f_64(self.distanceMeters, serializer);
  }

  @protected
  void sse_encode_strava_token_result(
    StravaTokenResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
    sse_encode_f_64(self.expiresAt, serializer);
  }

  @protected
  void sse_encode_strava_upload_ffi_error(
    StravaUploadFfiError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_upload_ffi_error_code(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_strava_upload_ffi_error_code(
    StravaUploadFfiErrorCode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_strava_upload_ffi_response(
    StravaUploadFfiResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_upload_ffi_status(self.status, serializer);
    sse_encode_opt_String(self.remoteId, serializer);
    sse_encode_bool(self.isDuplicate, serializer);
    sse_encode_opt_box_autoadd_strava_upload_retry(self.retry, serializer);
    sse_encode_opt_box_autoadd_strava_upload_ffi_error(self.error, serializer);
  }

  @protected
  void sse_encode_strava_upload_ffi_status(
    StravaUploadFfiStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_strava_upload_reservation(
    StravaUploadReservation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.handle, serializer);
  }

  @protected
  void sse_encode_strava_upload_retry(
    StravaUploadRetry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_strava_upload_retry_stage(self.stage, serializer);
    sse_encode_opt_String(self.uploadId, serializer);
    sse_encode_opt_box_autoadd_u_32(self.pollAttempt, serializer);
  }

  @protected
  void sse_encode_strava_upload_retry_stage(
    StravaUploadRetryStage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
